version: '3.8'

services:
  php:
    container_name: laravel_app
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./../news-website:/var/www/html
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: newssite
      MYSQL_USER: zizi
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ./../mysql-data:/var/lib/mysql

volumes:
  mysql-data: